[versions]
agp = "8.12.3"
core = "3.5.3"
coreSplashscreen = "1.0.1"
desugar_jdk_libs = "2.1.5"
firebaseBom = "34.4.0"
firebaseMessagingDirectboot = "25.0.1"
kotlin = "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinxDatetime = "0.7.1"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.10.00"
lifecycleViewmodelKtx = "2.9.4"
mapsCompose = "6.12.1"
materialIconsExtended = "1.7.8"
playServicesLocation = "21.3.0"
room = "2.8.2"
signalr = "10.0.0-rc.2.25502.107"
sqlcipher= "4.5.4"
sqlight = "2.6.1"
koin = "4.1.1"
kspVersion = "2.2.20-2.0.3"
serialize-kotlin = '2.2.20'
kotlinxSerializationJson = "1.9.0"
ktor = "3.3.1"
kotlinxCoroutinesPlayServices = "1.10.2"
coroutines = "1.10.2"
nav_version = "2.9.5"
constrain-compose = "1.1.1"
coilCompose = "2.7.0"
gms="4.4.4"
mapsUtilsKtx = "5.2.1"
playServicesMaps = "19.2.0"
qrKit = "3.1.3"
uiGraphics = "1.9.3"
ui = "1.9.3"
gradleSecret = "2.0.1"
zxingAndroidEmbedded = "4.3.0"


[libraries]
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
core = { module = "com.google.zxing:core", version.ref = "core" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "uiGraphics" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

#firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging-directboot = { module = "com.google.firebase:firebase-messaging-directboot",version.ref="firebaseMessagingDirectboot" }

#coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coilCompose" }



#room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

#signalr
signalr = { module = "com.microsoft.signalr:signalr", version.ref = "signalr" }

#qr package
#qr-kit = { module = "network.chaintech:qr-kit", version.ref = "qrKit" }

#sqlcipher
sqlcipher= {module= "net.zetetic:android-database-sqlcipher", version.ref= "sqlcipher"}
sql-light = { group = "androidx.sqlite", name = "sqlite", version.ref = "sqlight" }

#koin
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-nav = { group = "io.insert-koin", name = "koin-androidx-navigation", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }



#coroutines
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }


#kotlin services
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }

#ktor
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-loggin = { group = "io.ktor", name = "ktor-client-logging-jvm", version.ref = "ktor" }
ktor-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }

#serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }


#navigation
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "nav_version" }


#constrin layout
compose-constrin = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constrain-compose" }

#location
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
maps-utils-ktx = { module = "com.google.maps.android:maps-utils-ktx", version.ref = "mapsUtilsKtx" }

#lifecycle
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-compose-runntime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleViewmodelKtx" }
ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }

#map


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialize-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialize-kotlin" }

ksp-android = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
google-gms = { id = "com.google.gms.google-services", version.ref = "gms" }
map-secret = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "gradleSecret" }
